name: Build result

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system: [node12-linux-x64, node12-win-x64]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Install
      run: yarn install

    - name: Eslint Test
      run: yarn run lint

    - name: Build typescript
      run: yarn run build

    - name: Build pkg
      run: rm -rf src && mv build src && npx pkg --options max_old_space_size=4096 . -t ${{ matrix.system }} -o cloudreve-cli-${{ matrix.system }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: cloudreve-cli-${{ matrix.system }}
        path: cloudreve-cli-*
