name: Build result

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system: [node14-linux-x64]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Install
      run: yarn install

    - name: Eslint Test
      run: yarn run lint

    - name: Build typescript
      run: yarn run build

    - name: Build pkg
      run: rm -rf src && mv build/src src && npx pkg . -t ${{ matrix.system }} -o cloudreve-cli-${{ matrix.system }}

    - name: Upx bin
      run: |
        wget https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
        tar -xvJf upx-3.96-amd64_linux.tar.xz
        upx-3.96-amd64_linux/upx cloudreve-cli-*
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: cloudreve-cli-${{ matrix.system }}
        path: cloudreve-cli-*
